### ISSUE TITLE
Disables double-click to select

### ISSUE THREAD

**Issue by roaringskyinc** [sokolovstas/SublimeWebInspector#100]
In the latest Sublime Text 3, this package disables double-click to select on my system.

**Comment by priydes** [comment]
Taking a look.

**Comment by jerryni** [comment]
YES.I have same problem.

https://www.sublimetext.com/forum/viewtopic.php?f=3&p=70238

Remove web inspector, then the dbclick work well.

**Comment by danmosemsft** [comment]
Sorry. Should be fixed in commit 7239613d1 in release 7239613 which should be deployed in a couple hours.
