### ISSUE TITLE
On javascript files change, always pause and open the callstack

### ISSUE THREAD

**Issue by netsti** [sokolovstas/SublimeWebInspector#101]
Always when i make a change in a javascript file, reload the site and pause everything and not resume when i click in the icon, and the Javascript Callstack open but don,t work.

I have this configuration but not work too

{
	"enable_source_maps": false,
	"pause_on_exceptions": "none",
	"reload_on_start": true
}

**Comment by priydes** [comment]
Is this one similar to issue #99 ?

**Comment by priydes** [comment]
Looks like it is same as #99 .

**Comment by danmosemsft** [comment]
Workaround is "stop debugging" and then reattach.
