### ISSUE TITLE
Plugin for Cuda?

### ISSUE THREAD

**Issue by Alexey-T** [sokolovstas/SublimeWebInspector#107]
Good plugin. It is possible to make such for CudaText?

**Comment by danmosemsft** [comment]
I'm not familiar with CudaText, but at a glance it has a comparable extensibility API, so, perhaps. Among the requirements - you need to be able to run a web socket client; you need a way to draw breakpoint markers, and respond to clicks on them; highlight a line; and display callstack, locals, etc in  their own panes. Sublime allows you to draw a rectangular margin around text to make "buttons" - ideally you'd be able to do something like that.

Let me know if you do it!

**Comment by Alexey-T** [comment]
Tks. Cudatext is able but not all; it cannot add panels but i want to add it. To add panels.You interested to make port? (if I add panels)

**Comment by danmosemsft** [comment]
No, thanks though. I'll certainly keep an eye on it if you start the project. If CudaText becomes more popular, I could possibly contribute.
