### ISSUE TITLE
Chrome: window.postMessage

### ISSUE THREAD

**Issue by danielbeutner** [sokolovstas/SublimeWebInspector#115]
I get this warning from the Javascript Console when starting Chrome Canary in debug mode:

> [WRN] ---:160 'window.postMessage(message, transferables, targetOrigin)' is deprecated and will be removed in M54, around October 2016. Please use 'window.postMessage(message, targetOrigin, transferables)' instead. See https://www.chromestatus.com/features/5719033043222528 for more details.

**Comment by danmoseley** [comment]
That is logged by the browser about the page. You should see the exact same message in the built in developer tools' console.
