### ISSUE TITLE
could not attach to chrome 

### ISSUE THREAD

**Issue by reihor** [sokolovstas/SublimeWebInspector#118]
2017-01-11 16:56:16.755 Google Chrome[694:14502] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7f8cd88cb860>. Break on NSLog to debug.
2017-01-11 16:56:16.755 Google Chrome[694:14502] Call stack:
(
    "+callStackSymbols disabled for performance reasons"
)
objc[694]: __weak variable at 0x7f8cd88b3970 holds 0x2121212121212121 instead of 0x7f8cd889e3d0. This is probably incorrect use of objc_storeWeak() and objc_loadWeak(). Break on objc_weak_error to debug.

**Comment by danmoseley** [comment]
Hi @reihor my time is spent on other projects now so I can't take a look anytime soon. 

First thing as the readme.md in master says: 

If it won't get past "Start Google Chrome":

If Chrome was already open when Sublime launches it with the debugger flag, Chrome won't open the port, so the debugger can't attach. Close all instances of Chrome and try again.

If that doesn't help maybe it's a bug or change in Chrome. Hook up a debugger (the free Visual Studio Python debugger seems to be the best -- I put instructions in https://github.com/sokolovstas/SublimeWebInspector/issues/113 -- and set [debug mode](https://github.com/sokolovstas/SublimeWebInspector/blob/ST3/swi.py#L67) and/or [web socket tracing](https://github.com/sokolovstas/SublimeWebInspector/blob/ST3/websocket.py#L82)

Having said that the actual error output you have below looks like normal output from Chrome's internals or the web page itself. You probably see the same in Chrome's own dev tools. This also suggests that you ARE attached. What makes you think you aren't? 

AGain I"d take a look through https://github.com/sokolovstas/SublimeWebInspector/blob/master/README.markdown
to see if it helps

**Comment by reihor** [comment]
Thanks a lot. 
I have read the readme.md when I installed  SublimeWebInspector the first time.
Now when I started Google Chrome with remote debug port 9222,  Chrome was opened with a new tab. Chrome won't open the test website.

http://127.0.0.1:9222/json

[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/872973cb-895c-4256-b134-092dc0bf41db",
   "faviconUrl": "https://www.google.co.jp/favicon.ico",
   "id": "872973cb-895c-4256-b134-092dc0bf41db",
   "title": "New Tab",
   "type": "page",
   "url": "http://127.0.0.1:9222/json",
   "webSocketDebuggerUrl": "ws://127.0.0.1:9222/devtools/page/872973cb-895c-4256-b134-092dc0bf41db"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/e86d711c-b262-4d25-881c-92976ed44b5a",
   "id": "e86d711c-b262-4d25-881c-92976ed44b5a",
   "title": "Worker pid:2297",
   "type": "service_worker",
   "url": "https://www.google.co.jp/_/chrome/newtab-serviceworker.js",
   "webSocketDebuggerUrl": "ws://127.0.0.1:9222/devtools/page/e86d711c-b262-4d25-881c-92976ed44b5a"
} ]

**Comment by danmoseley** [comment]
Can you navigate manually to it? If not, unfortunately you'll have to debug. I found the Python debugging experience in VS to be good, and it works in the free edition.

I don't expect to have time to look at this project in coming months. If folks find it useful, PRs are welcome (although I won't have time to test them either!)
