### ISSUE TITLE
[Bug] Error from debuggee: 'Debugger.canSetScriptSource' wasn't found

### ISSUE THREAD

**Issue by Kristinita** [sokolovstas/SublimeWebInspector#119]
### 1. Summary

(Если не возражаете, по-русски буду писать)

Не получается начать пользоваться Web Inspector. Получаю ошибку в консоли.

### 2. Expected behavior

Успешное начало пользования Web Inspector.

### 3. Actual behavior

```
key evt: shift+control+p
command: show_overlay {"overlay": "command_palette"}
command: swi_debug
SWI: Connecting to ws://127.0.0.1:9222/devtools/page/78d13acd-09ad-4759-8e50-74363c4c4d27
SWI: Thread started
SWI: WebSocket opened
Error from debuggee: 'Debugger.canSetScriptSource' wasn't found
```

### 4. Steps to reproduce

Проблема воспроизводится для меня в Sublime Text без плагинов и пользовательских настроек.

Установил Web Inspector через Package Control → перезагрузил Sublime Text. Путь к исполняемому файлу Chrome у меня такой же, как и по умолчанию; в настройках SWI параметру `debug_mode` присвоил значение true. <kbd>Ctrl+Shift+P</kbd> → `Web Inspector` → `Start Debugging` → в появившемся меню выбираю открытый в Chrome файл скрипта → получаю ошибку. У меня открываются внизу 2 пустых pane; какие бы действия не предпринимал, в них ничего не появляется.

![Web Inspector panes](http://i.imgur.com/3kP8n5v.png)

### 5. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**Chrome:**
Version 55.0.2883.87 m (64-bit)

Спасибо.

**Comment by sokolovstas** [comment]
If your target is Chrome, make sure any existing instances are **closed**.

Press CTRL+SHIFT+R (⌘ + SHIFT + R) and select "**Start Google Chrome with remote debug port 9222**". (If CTRL+SHIFT+R didn't work, do CTRL+SHIFT+P and choose Web Inspector. Also, check the Sublime console for error messages.)

Важные части отмечены жирным начертанием

**Comment by Kristinita** [comment]
@sokolovstas, я закрыл Chrome → <kbd>Ctrl+Shift+P</kbd> → `Web Inspector` → `Start Google Chrome with remote debug port 9222` → открылся Chrome с вкладкой `file:///C:/Program%20Files%20(x86)/Google/Chrome/Application/55.0.2883.87/`

![Вкладка Chrome](http://i.imgur.com/StpFd0Z.png)

При этом в Sublime Text открывается панель с вот такими ошибками:

> [3792:3248:0125/143020:ERROR:policy_loader_win.cc(449)] PReg file doesn't exist: C:\WINDOWS\System32\GroupPolicy\User\Registry.pol
[3792:5584:0125/143026:ERROR:policy_loader_win.cc(449)] PReg file doesn't exist: C:\WINDOWS\System32\GroupPolicy\User\Registry.pol

![Панель](http://i.imgur.com/xOYJtAo.png)

В консоли Sublime Text, несмотря на `debug_mode = true` и настроенный на максимальные значения пакет [**Logging Control**](https://packagecontrol.io/packages/Logging%20Control), получаю только следующее:

```
command: swi_debug
Running C:\Program Files (x86)\Google\Chrome\Application\chrome.exe --remote-debugging-port=9222
```

Что делать дальше — не пойму. Если [**открываю мой файл в Chrome**](http://ru.stackoverflow.com/a/587973/199934) и запускаю `Start Debugging` из command palette, получаю то же поведение, что и в моём первом посте.

Спасибо.

**Comment by Kristinita** [comment]
Проблема не разрешена.

Спасибо.

**Comment by sokolovstas** [comment]
Ну я понимаю ошибка есть, но при этом например может вывод в консоль есть SWI есть? Оно может работает?

**Comment by Kristinita** [comment]
@sokolovstas , больше в консоли ничего нет, кроме того, что написал в предыдущем посте.

Спасибо.

**Comment by sokolovstas** [comment]
Можно попробовать сделать reload page

**Comment by sokolovstas** [comment]
![screen shot 2017-01-25 at 16 57 53](https://cloud.githubusercontent.com/assets/14689/22289855/7f4f7dbe-e31f-11e6-8a2b-844297e0f90f.png)

**Comment by sokolovstas** [comment]
У меня есть такая же ошибка и все работает нормально
SWI: WebSocket opened
Error from debuggee: 'Debugger.canSetScriptSource' wasn't found

Всего лишь навсего когда то из хрома убрали эту функцию. И необходимо обновить плагин, но времени на это к сожалению нету.

**Comment by Kristinita** [comment]
@sokolovstas , на каком этапе следует выполнить `Reload page`?

Спасибо.

**Comment by sokolovstas** [comment]
If your target is Chrome, make sure any existing instances are closed.

Press CTRL+SHIFT+R (⌘ + SHIFT + R) and select **"Start Google Chrome with remote debug port 9222".** (If CTRL+SHIFT+R didn't work, do CTRL+SHIFT+P and choose Web Inspector. Also, check the Sublime console for error messages.)

Go to Sublime press CTRL+SHIFT+R and select "Start debugging" and **select your tab** in the list provided. It will select it automatically if there is only one open.

CTRL+SHIFT+R (⌘ + SHIFT + R) and Reload page
(If CTRL+SHIFT+R didn't work, do CTRL+SHIFT+P and choose Web Inspector->Reload page)

**Comment by Kristinita** [comment]
> and select your tab

Как я могу выбрать вкладку, если помимо `file:///C:/Program%20Files%20(x86)/Google/Chrome/Application/55.0.2883.87/` других открытых вкладок в Chrome нет?

Спасибо.

**Comment by sokolovstas** [comment]
Если вкладка одна то он открывает текущую, ничего выбирать не надо, просто проверить релоад

**Comment by Kristinita** [comment]
> Если вкладка одна то он открывает текущую, ничего выбирать не надо, просто проверить релоад

Вкладка одна в Sublime Text или Chrome?

**Comment by sokolovstas** [comment]
В хроме.

Press CTRL+SHIFT+R (⌘ + SHIFT + R) and select "Start Google Chrome with remote debug port 9222". (If CTRL+SHIFT+R didn't work, do CTRL+SHIFT+P and choose Web Inspector. Also, check the Sublime console for error messages.)

Закройте все вкладки, откройте yandex.ru и google.ru

Go to Sublime press CTRL+SHIFT+R and select "Start debugging" and select your tab in the list provided. It will select it automatically if there is only one open.

Выберите одну из вкладок и попробуйте сделать релоад

CTRL+SHIFT+R (⌘ + SHIFT + R) and Reload page
(If CTRL+SHIFT+R didn't work, do CTRL+SHIFT+P and choose Web Inspector->Reload page)

**Comment by Kristinita** [comment]
Сделано. Вкладки с Yandex и Google перезагружаются при `Reload page`. Но panes в Sublime Text по-прежнему пустые.

Спасибо.

**Comment by sokolovstas** [comment]
Дальше читайте про брейкпоинты дебаггинг и прочее. Вопрос исчерпан.

**Comment by danmoseley** [comment]
Good to see you back @sokolovstas ! My team priorities changed, I moved to the  .NET Framework team, so I expect little or no SWI contributions now. We never finished the work in the DOM explorer branch -- perhaps one day someone will take that up.

**Comment by sokolovstas** [comment]
@danmosemsft Thank you and your team for the efforts and hard work on this tool. For now I don't have time too. And my primary editor now is Atom.

**Comment by danmoseley** [comment]
@sokolovstas 
Just thought I'd mention -- if you have any interest in .NET, my new world, there's plenty of opportunities to be involved at the [library](https://github.com/dotnet/corefx/issues?q=is%3Aissue+is%3Aopen+label%3A%22up+for+grabs%22) or [runtime](https://github.com/dotnet/coreclr/issues?q=is%3Aissue+is%3Aopen+label%3A%22up+for+grabs%22) level according to your interest. There is no need to have a Windows machine - we run equally on OSX and Linux. It can be fun to make a change that helps 100K's of developers!
