### ISSUE TITLE
Script not reloading

### ISSUE THREAD

**Issue by Draivin** [sokolovstas/SublimeWebInspector#24]
When `set_script_source` is true in the config, after the first file save, the scripts are not updated in the browser, instead the logs appear like this:
![image](https://f.cloud.github.com/assets/947593/278012/d8580af8-90d9-11e2-9125-32a379ee37ac.png)

If I try to save the script again after this, I get this error:
![image](https://f.cloud.github.com/assets/947593/278005/807149d0-90d9-11e2-8fb8-c37052209292.png)

**Comment by danmosemsft** [comment]
For the console issue, I tried the repro, and it works perfectly always.
For the error stack, it is not possible to determine what might have caused this,  and code in Sublime and the package has changed.
For all breakpoints being added as disabled, this also is fixed now.
