### ISSUE TITLE
Compatibility with CoffeeScript?

### ISSUE THREAD

**Issue by jonarrien** [sokolovstas/SublimeWebInspector#28]
I would like to know if there is some way to use this plugin with coffeescript. As Ruby developer, i don't compile the source code into javascript until production deployment.

**Comment by m1sta** [comment]
+1

**Comment by danmosemsft** [comment]
Resolving as a duplicate of #55, which came later but has a more general title. It seems there is nothing specific here to CoffeeScript, that would not also apply to Typescript, etc. Essentially, source maps need to work.
