### ISSUE TITLE
Disabled Breakpoints In OSX

### ISSUE THREAD

**Issue by stationkeeping** [sokolovstas/SublimeWebInspector#46]
I finally managed to get this working with Chrome Canary, but breakpoints don't work properly. I am unable to add breakpoints while debugging. I can add them if I stop debugging, but the debugger doesn't break on them. 

If I look in my user settings, I see they are disabled:

```
{
	"breaks":
	{
		"/path/to/file/AppController.js":
		{
			"50":
			{
				"status": "disabled"
			},
			"92":
			{
				"breakpointId": "None",
				"status": "disabled"
			}
		},
		"/path/to/file/AppController.js":
		{
		}
	},
	"chrome_path":
	{
		"osx": "/Applications/GoogleChromeCanary.app/Contents/MacOS/Google Chrome Canary"
	}
}
```

So how do I enable them?

**Comment by danmosemsft** [comment]
I'm going to close this as it's very old and not actionable.
