### ISSUE TITLE
Menu state for 'Stop Debugger' / 'Start Debugger' inaccurate

### ISSUE THREAD

**Issue by Iristyle** [sokolovstas/SublimeWebInspector#5]
Steps to repro locally

* Ensure no instances of Canary are running
* Launch a new instance of Chrome from Sublime - `Start Google Chome with remote debug port 9222`
* Navigate to a page of your choosing
* Open command palette - select `Web Inspector`, then `Start Debugging`
* SWI Console opens
* Open command palette - select `Web Inspector`, then `Stop Debugging`
* Close `Chrome Canary`

Now, reopen the command palette and select `Web Inspector`

The same `Stop Debugging` choice is there along with `Reload Page`, `Clear Console` and `Add/Remove Breakpoint`

Only way for me to get the original menu item back with `Start Debugging` is to kill and restart Sublime.

**Comment by danmosemsft** [comment]
This does not reproduce and presumably was fixed in the last 2 years.
