### ISSUE TITLE
Support source maps to debug through original source code

### ISSUE THREAD

**Issue by kevindurb** [sokolovstas/SublimeWebInspector#55]
I have a project I compile with grunt and browserify and the grunt-browserify task adds a base-64 encoded source map to the compiled javascript. Chrome sees the source map and lets me debug the uncompiled files, but swi only maps the compiled file.

**Comment by lefoy** [comment]
I would also love this!

**Comment by danmosemsft** [comment]
We plan to do this, although not immediately - so it works well with Typescript.

**Comment by hems** [comment]
kool
+21

**Comment by danmosemsft** [comment]
This is now merged into ST3 but we haven't cut a release. Needs some stabilization.

**Comment by danmosemsft** [comment]
Released. Please create new issues with any feedback.
