### ISSUE TITLE
URLs with GET aren't mapped

### ISSUE THREAD

**Issue by mrliptontea** [sokolovstas/SublimeWebInspector#59]
Hi,

small sugestion:

I usually use something like ?ver=[version_hash] for production environment and timestamp hash for developers in order to force file reload. Because of this, SWI cannot find files with names like script.js?ver=eabc097c, which is by the way incorrect file name for having '?' in it.

Simple solution would be to add something like this in scriptParsed method:
```Python
url_parts[-1] = re.sub(r"\?.*$", "", url_parts[-1])
```

I won't bother to make pull request for this, because maybe there's better way to write this and it's only this one line to add.

Thank you for this great plugin!

**Comment by danmosemsft** [comment]
I can't reproduce this. I have a file app.js but I include it like
    <script src="app.js?ver=12345"></script>
Now when I debug, the debugger gives back "app.js", ie., the real file name, and it all works fine. So unless you're somehow putting ? in the name of the actual file, or I'm missing the point, then some change in Chrome has fixed this...?

**Comment by mrliptontea** [comment]
Whoa, yeah, I reported this almost two years ago. Frankly, I haven't used SWI in a long time, but I'll give it a try.

**Comment by danmosemsft** [comment]
Yep, I'm trying to put a bit of Microsoft resources into stabilizing it and giving it better Typescript and IE support, and a DOM explorer. I suspect a lot of people tried it and gave up, in the past.

**Comment by danmosemsft** [comment]
Nope, it reproes.

**Comment by danmosemsft** [comment]
Fixed
