### ISSUE TITLE
Wrong focus after reload

### ISSUE THREAD

**Issue by alexandernst** [sokolovstas/SublimeWebInspector#64]
Plugin works perfectly, except that it insists it focusing the SWI Console tab instead of the tab that triggered the save action.

**Comment by pcunite** [comment]
As a work around, open the "swi.py" file, search for the function "def find_view" and comment out (using #) the **window.focus_view(v)** call. Currently, this is on line 913.

**Comment by danmosemsft** [comment]
Can you please try this in the latest release (st3-1.6.4)? I can't reproduce anything like this and the relevant code has changed substantially in the last week or so.

Please do reactivate if it still happens, with some steps I can use to reproduce. thanks
