### ISSUE TITLE
Stop closing tabs

### ISSUE THREAD

**Issue by alexandernst** [sokolovstas/SublimeWebInspector#65]
Web inspector should not close any tabs not related to Web inspector itself. 

It's completely annoying to stop debugging and get some (random?) tabs closed because of the re-layout. Best thing is to just remove the whole layout "feature" and just open a tab in the first available layout and let the user layout the UI as he wants to.

**Comment by danmosemsft** [comment]
As the code is, I don't think it closes any tabs. Probably Stanislav changed it. It ought to close at least its own tabs. That I will fix. 
I am not sure if you are asking to not have it create new groups for the Console and Stack. I think that part is good as is unless I am missing some separate problem.

**Comment by danmosemsft** [comment]
ce2b4a2411f should make sure all SWI's tabs are closed, at least on starting chrome, starting debugging, and stopping debugging. (Also console, stack etc are closed on resuming execution)

If you have a repro for closing /your/ tabs, please share and reopen.
