### ISSUE TITLE
"Start Google Chrome with remote debug port 9222" opens a blank page

### ISSUE THREAD

**Issue by eyalzek** [sokolovstas/SublimeWebInspector#66]
What am I doing wrong?

**Comment by ivictbor** [comment]
Just ignore blank page and try to got to http://localhost:9222/json first, then go to devtoolsFrontedURL:

![](https://faststatic.devforth.io/main/VfPTj443eea6GnQuBSrdDi.webp)

Here is a detailed guide which I wrote: https://devforth.io/blog/chrome-remote-debugging-setup/
