### ISSUE TITLE
No "SWI breakpoint stack" tab shown

### ISSUE THREAD

**Issue by kharv** [sokolovstas/SublimeWebInspector#70]
I'm using Sublime 2 and Web Inspector. When I start debugging, there's only one "SWI Console" tab appearing. The other tabs as "SWI breakpont stack" or "Object evaluate breakpoint local" do not shown up. I am able to set a breakpoint though. Don't know if I mis-configure anything. Any help? Thanks.

![screenshot from 2014-08-15 15 45 21](https://cloud.githubusercontent.com/assets/7249870/3931456/89d065d8-2458-11e4-9d8f-22a7397d0eb8.png)

**Comment by danmosemsft** [comment]
I'm going to assume this was fixed by doing that..
