### ISSUE TITLE
No Settings in Sublime 3 Package

### ISSUE THREAD

**Issue by gravidThoughts** [sokolovstas/SublimeWebInspector#74]
Hi,

Just installed this with Sublime 3 Package Control on Windows 7, and when you open the default settings, it is empty.

Based on your you tube video, their appeared to be several settings. I have not tried to use it yet, and it may still work. I just wanted to make you aware that this is the case.

**Comment by nbppp2** [comment]
So i worked around this by doing the following in the terminal

```
mkdir ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/Web\ Inspector\ 3
subl ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/Web\ Inspector\ 3/swi.sublime-settings
```

This assumes you have setup a symbolic link for sublime. Copy the settings from here https://raw.githubusercontent.com/sokolovstas/SublimeWebInspector/ST3/swi.sublime-settings, as @Leolik stated, and save the file. That should get you going with settings.

**Comment by Darkle** [comment]
Looks like the issue might be here: https://github.com/sokolovstas/SublimeWebInspector/blob/ST3/Main.sublime-menu#L69

I think `"args": {"file": "${packages}/Web Inspector 3/swi.sublime-settings"},`  should be `"args": {"file": "${packages}/Web Inspector/swi.sublime-settings"},`

**Comment by sokolovstas** [comment]
@Darkle Thanks! Fixed.

**Comment by hems** [comment]
i just installed from sublime package manager and still no settings for me.

**Comment by hems** [comment]
@nbppp2 i followed your instructions and it still don't read the settings file i just added, still trying the default google chrome path.
