### ISSUE TITLE
x64 Windows Unsupported?

### ISSUE THREAD

**Issue by gravidThoughts** [sokolovstas/SublimeWebInspector#75]
Get the following in Sublime console when trying to launch Google on the debug port.   

File "swi in C:\Users\ccopelm2\AppData\Roaming\Sublime Text 3\Installed Packages\Web Inspector.sublime-package", line 253, in run KeyError: 'windows_x64'

Does it not support x64 Windows?

I set the chrome_path as follows

	"chrome_path": {
		"osx": "",
		"windows": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
		"linux": ""
	},

**Comment by danmosemsft** [comment]
The bug is that sublime.arch() returns x86 even on x64 OS presumably because it's a 32 bit app.

**Comment by danmosemsft** [comment]
Fixed by 89d04d85
