### ISSUE TITLE
Can't get sublimetextwebinspector working

### ISSUE THREAD

**Issue by casemanx** [sokolovstas/SublimeWebInspector#78]
I wonder if its ok to post a question here about getting sublimetextwebinspector working. I've been trying for several days. If this is the wrong place to post such a question could someone point me to the right place?  The sublime text forum have been down the whole time. Are they ever up? 

If its OK to ask, whenever I to try click on "Start Google Chrome with remote debug port 9222" I get the following error message.

[Errno 13] Permission denied
[cmd: ['/Applications/Google Chrome.app', '--remote-debugging-port=9222', '--profile-directory=Default','']]
[dir: /Users/caseymandell/Dropbox/Documents/sublimeProjects/Experiments/src/scripts]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]

 I have no real expertise in these matters at all. From searching the web I've gleaned that one of the first things to do is see if my browser will run  http://127.0.0.1:9222/json.  None of my browsers, (Firefox, Aurora, Chrome, Canary or Safari) will run this url which must be telling, but after quite a bit of searching, I can't find out what it means or what to do about it. If there's any other information I need to furnish please tell me what it is and I'll gladly furnish it. I'm dying to use the debugger. My swi.sublime-settings file follows. (I'm on a Mac.)

{
"chrome_path":{
	//"osx" : "/Applications/Google Chrome Canary.app --remote-debugging-port=9222 --no-first-run --no-default-browser-check --user-data-dir=$(mktemp -d -t 'chrome-remote_data_dir'",
	//"osx": "/usr/sbin/Google Chrome Canary.app",
	"osx":"/Applications/Google Chrome.app",
	//"osx" : "Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
	"windows": "C:\\Program Files\\Google\\Chrome\\chrome.exe",
"linux": "/usr/bin/google-chrome"
},
"chrome_profile": "Default",
"chrome_remote_port": "9222",
"breakpoint_scope": "swi.breakpoint",
"current_line_scope": "swi.current",
"interactive_scope": "mcol_0088CCFF.settings",
"stack_layout": {
"cols": [0.0, 0.6, 1.0],
"rows": [0.0, 0.7, 1.0],
"cells": [[0, 0, 2, 1], [0, 1, 1, 2], [1, 1, 2, 2]]
},
"console_layout": {
"cols": [0.0, 0.6, 1.0],
"rows": [0.0, 0.7, 1.0],
"cells": [[0, 0, 2, 1], [0, 1, 1, 2], [1, 1, 2, 2]]
},
"reload_on_start": false,
"reload_on_save": true,
"reload_timeout": 0,
"user_agent": "",
"set_script_source": false,
"open_stack_current_in_new_tab": false,
"breaks": {}
}

**Comment by nbppp2** [comment]
My resolution for this was to get the settings file setup correctly. #74 shows my resolution for this.

**Comment by nbppp2** [comment]
@casemanx you seem to have commented out the path to the chrome executable. 

In OSX applications with the '.app' extension are actually just folders. The actual executable is in a specific location in that folder. 

So your line 

```"osx":"/Applications/Google Chrome.app"```

should actually be 

```"osx": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"```

so that is actually points at the chrome executable.

**Comment by casemanx** [comment]
Thanks you very much for your reply! I'm super busy right now, but I'll 
give it a try.
Sincerely,
Casey

Daniel Weber wrote:

**Comment by danmosemsft** [comment]
Since there were no more comments I'm going to assume this solved the problem.
