### ISSUE TITLE
Add Mac shortcuts for opening chrome in debug mode in readme file

### ISSUE THREAD

**Issue by richbrill** [sokolovstas/SublimeWebInspector#80]

**Comment by danmosemsft** [comment]
I don't have a Mac handy.... can someone suggest what's needed?

**Comment by danmosemsft** [comment]
The are defined in [here](https://github.com/sokolovstas/SublimeWebInspector/blob/ST3/Default%20(OSX).sublime-keymap)

There currently is't one for starting Chrome.

**Comment by danmosemsft** [comment]
I tried to add a shortcut for starting Chrome but it wasn't very clean. I've put this aside. Meanwhile all the keypresses are on the readme.
