### ISSUE TITLE
unable to make breakpoints work

### ISSUE THREAD

**Issue by dreaganluna** [sokolovstas/SublimeWebInspector#81]
I'm able to create a breakpoint, and it is added viasually in my ST. The break entry is also created in the settings file, but it is added as:
"C:\\inetpub\\wwwroot\\scripts\\thisfilename.js":
{
	"1042":
	{
		"breakpointId": "none",
		"status": "disabled"
	}
}

The breakpoints window does not show up and teh code does not halt when passing the breakpoint.

**Comment by danmosemsft** [comment]
I can't reproduce this. I have seen it get confused when re-attaching, but I need to find repro steps.
