### ISSUE TITLE
Connect to SFTP

### ISSUE THREAD

**Issue by John316** [sokolovstas/SublimeWebInspector#83]
Can I connect via SFTP to debug a web site with SublimeWebInspector or I dont need this for work with site on server?
Can I use WebInspector if all of my scripts combine to one js file?

**Comment by danmosemsft** [comment]
The location of the server should not be important as it connects to the browser, which should be of course local.

For your second question, currently it does not support source maps. These contain the information necessary to map a location in the running file to a location in the original file. You would have to debug directly in the combined file and that should work fine. #55 is a feature request for source maps.
