### ISSUE TITLE
'Debugger.setOverlayMessage' is not supported?

### ISSUE THREAD

**Issue by taydakov** [sokolovstas/SublimeWebInspector#84]
Sublime Text shows annoying "'Debugger.setOverlayMessage' wasn't found" pop-up message every time debugger stops on a breakpoint or resumes. I commented https://github.com/sokolovstas/SublimeWebInspector/blob/ST3/swi.py#L345 and https://github.com/sokolovstas/SublimeWebInspector/blob/ST3/swi.py#L377 to get rid of them for the time being.

My environment:
 - Sublime Text build 3065
 - Google Chrome version 42.0.2305.2 canary (64-bit)
 - the latest version of Sublime Web Inspector (where to find the exact version?)
 - Chrome Debug Port is 9229

Network dump using "ngrep -d lo0 port 9229":
**T 127.0.0.1:9229 -> 127.0.0.1:53731 [AP]**
  .~.}{"method":"Debugger.paused","params":{"callFrames":[{"callFrameId":"{\"ordinal\":0,\"injectedScriptId\":6}","functionName":"","location":{"scriptId":"34","lineNumber":3,"columnNumber":1},"scopeChain":[{"object":{"type":"object","objectId":"{\"injectedScriptId\":6,\"id\":2}","className":"Object","description":"Object"},"type":"local"},{"object":{"type":"object","objectId":"{\"injectedScriptId\":6,\"id\":3}","className":"Window","description":"Window"},"type":"global"}],"this":{"type":"object","objectId":"{\"injectedScriptId\":6,\"id\":4}","className":"Window","description":"Window"}}],"reason":"other","hitBreakpoints":["34:3:0"]}}
**T 127.0.0.1:53731 -> 127.0.0.1:9229 [AP]**
  .....d..b...+Q..)...j...1D..f...j...1D..j...oD..+7..g...+3..+-..{...d...'D..n...oF..) ..~...yJ...+..y...F...j...v
**T 127.0.0.1:9229 -> 127.0.0.1:53731 [AP]**
  .V{"error":{"code":-32601,"message":"'Debugger.setOverlayMessage' wasn't found"},"id":5}
**T 127.0.0.1:53731 -> 127.0.0.1:9229 [AP]**
  .....y."y[.F C...Y.Rc..Oq[..y[.Ul).Mr..Vk...8Y.Pw... ..Hg..kf[.. ...k..Ga..FQ..Kr..F^[...%.Kf%..0.._.Y.Og..Mf[.. +.Lv..G,..VR..Rg..Kg.._

Binary representation of the second message from the above using "ngrep -xX -d lo0 port 9229":
T 127.0.0.1:54015 -> 127.0.0.1:9229 [AP]
  81 eb f0 c9 d2 ce 8b eb    bb aa d2 f3 f2 fb dc e9    ................
  f0 be 91 bb b3 a3 83 eb    e8 ee 8b eb bf ab 83 ba    ................
  b3 a9 95 eb e8 ee d2 99    b3 bb 83 ac b6 ee 99 a7    ................
  f2 9d 85 ab be a7 9d ac    f2 99 95 ab f2 87 9e ba    ................
  a2 ab 93 bd bd bc d2 b4    fe ee d2 a4 b7 ba 98 a6    ................
  b6 ec ca e9 f0 8a 95 ab    a7 a9 97 ac a0 e0 83 ac    ................
  a6 81 86 ac a0 a2 91 b0    9f ab 83 ba b3 a9 95 eb    ................
  af                                                    .

**Comment by sameernyaupane** [comment]
I have the same issue every time the debugger hits a breakpoint. It shows  the pop up message. 'Debugger.setOverlayMessage' wasn't found

**Comment by yesubabuch** [comment]
I too have the same issue...
![sublime-error](https://cloud.githubusercontent.com/assets/6448277/7797066/b2821072-0304-11e5-9928-99aa259c119a.png)

**Comment by danmosemsft** [comment]
Fixed by 91f8192. Looks like I committed it twice somehow, I'll fix that if I can figure out how.
