### ISSUE TITLE
Cant add breakpoint on MacOSX Mavericks

### ISSUE THREAD

**Issue by dopatraman** [sokolovstas/SublimeWebInspector#85]
After hitting CMD + Shift + R, I can start a browser session on the right port, but i cant add breakpoints.

**Comment by danmosemsft** [comment]
Have you attached? (After the launch, you must do CMD+Shift+R again, choose "Start debugging", and choose your tab of choice.)

Can you hit a breakpoint triggered by a "debugger;" keyword in your javascript? 

After setting a breakpoint, do you get an icon in the gutter?

If you go to Preferences>Packages>Web Inspector>Settings - User, do you see your breakpoint/s serialized?

**Comment by danmosemsft** [comment]
Do show mappings ... if you don't see a mapping one possible cause is that you didn't open the /folder/ that the sources is in. See issue #92

**Comment by danmosemsft** [comment]
I'm going to close this as I haven't got a Mavericks box and it works on Yosemite. Without more info I have to assume one of the various issues above.
